name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        ls -la /bin
        ls -la /sbin
        ls -la /usr/bin
        ls -la /usr/sbin
        which ulimit
        sudo ulimit -Sn 65536
        echo Add other actions to build,
        echo test, and deploy your project.
