name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ulimit -n
      run: 
        which ulimit
    - name: sudo sh -c 'ulimit -n'
      run: 
        sudo sh -c 'ulimit -n'
    - name: ls -l /bin
      run: 
        ls -l /bin
    - name: ls -l /sbin
      run: 
        ls -l /sbin
